#include "desktop_platform.h"

#if !defined(__EMSCRIPTEN__) && !defined(__ANDROID__)

#include <iostream>

namespace polarclock {

DesktopPlatform::DesktopPlatform() = default;

DesktopPlatform::~DesktopPlatform() {
    shutdown();
}

bool DesktopPlatform::init(int width, int height, const char* title) {
    if (!glfwInit()) {
        std::cerr << "Failed to initialize GLFW" << std::endl;
        return false;
    }

    // Set OpenGL version hints
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);

#ifdef __APPLE__
    // macOS requires forward compat and core profile
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
#else
    // Use compatibility profile for better Mesa/driver support on Linux
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_COMPAT_PROFILE);
#endif

    glfwWindowHint(GLFW_SAMPLES, 4);  // MSAA
    glfwWindowHint(GLFW_FOCUSED, GLFW_TRUE);

    m_window = glfwCreateWindow(width, height, title, nullptr, nullptr);
    if (!m_window) {
        std::cerr << "Failed to create GLFW window" << std::endl;
        const char* description;
        glfwGetError(&description);
        if (description) {
            std::cerr << "GLFW Error: " << description << std::endl;
        }
        glfwTerminate();
        return false;
    }

    glfwMakeContextCurrent(m_window);

    // Verify context is current
    if (glfwGetCurrentContext() != m_window) {
        std::cerr << "Failed to make OpenGL context current" << std::endl;
        return false;
    }

    // Initialize GLEW
    glewExperimental = GL_TRUE;
    GLenum glewErr = glewInit();
    if (glewErr != GLEW_OK) {
        // GLEW can report errors even when it works - just log it
        std::cerr << "GLEW warning: " << glewGetErrorString(glewErr) << std::endl;
    }
    // Clear any GL errors generated by GLEW
    while (glGetError() != GL_NO_ERROR) {}

    // Verify OpenGL is actually working
    const char* version = reinterpret_cast<const char*>(glGetString(GL_VERSION));
    if (!version) {
        std::cerr << "OpenGL not working - glGetString returned null" << std::endl;
        return false;
    }
    std::cout << "OpenGL initialized: " << version << std::endl;

    // Enable VSync
    glfwSwapInterval(1);

    // Enable MSAA
    glEnable(GL_MULTISAMPLE);

    m_lastTime = std::chrono::high_resolution_clock::now();
    return true;
}

void DesktopPlatform::shutdown() {
    if (m_window) {
        glfwDestroyWindow(m_window);
        m_window = nullptr;
    }
    glfwTerminate();
}

void DesktopPlatform::runMainLoop(std::function<void(float deltaTime)> frameCallback) {
    while (!shouldClose()) {
        auto currentTime = std::chrono::high_resolution_clock::now();
        float deltaTime = std::chrono::duration<float>(currentTime - m_lastTime).count();
        m_lastTime = currentTime;

        // Cap deltaTime to prevent animation skip after window unfocus
        if (deltaTime > 0.1f) {
            deltaTime = 0.1f;
        }

        frameCallback(deltaTime);
    }
}

void DesktopPlatform::getFramebufferSize(int& width, int& height) {
    glfwGetFramebufferSize(m_window, &width, &height);
}

void DesktopPlatform::swapBuffers() {
    glfwSwapBuffers(m_window);
}

void DesktopPlatform::pollEvents() {
    glfwPollEvents();
}

bool DesktopPlatform::shouldClose() {
    return glfwWindowShouldClose(m_window);
}

} // namespace polarclock

#endif // Desktop only
